# Generated by Django 4.2.4 on 2023-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='medioDePago',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
