# Generated by Django 4.2.6 on 2023-10-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_flujocaja_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
